version: "2"
services:
  web:
    build: .
    image: "pepitas"
    container_name: "pepitas"
    volumes: 
        - ./pepitas:/usr/src/app
        - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      #   MONGO_URL: "mongo"
      #   MONGO_DB_NAME: "comments"
      #   NODE_ENV: "development"
      PORT: 3000
  mongo:
    image: mongo
    ports:
      - "27017:27017"
